#!/usr/bin/env python3
"""Generate the shared Swift/Python model feature contract from one manifest."""

from __future__ import annotations

import argparse
import json
import math
import subprocess
import tempfile
from pathlib import Path
from typing import Any, cast


def load_manifest(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as source:
        return cast(dict[str, Any], json.load(source))


def expanded_names(manifest: dict[str, Any]) -> tuple[list[str], list[str]]:
    sleep = cast(dict[str, Any], manifest["sleep"])
    sleep_names = [f"current.{name}" for name in cast(list[str], sleep["current"])]
    for lag in range(1, int(sleep["lagCount"]) + 1):
        sleep_names.extend(f"lag{lag}.{name}" for name in cast(list[str], sleep["lag"]))
    sleep_names.extend(f"summary.{name}" for name in cast(list[str], sleep["summary"]))
    sleep_names.extend(f"agreement.lag{lag}" for lag in range(1, int(sleep["agreementCount"]) + 1))
    sleep_names.append("agreement.weighted")

    recovery = cast(dict[str, Any], manifest["recovery"])
    recovery_names = [f"sleep.{name}" for name in sleep_names]
    recovery_names.extend(f"current.{name}" for name in cast(list[str], recovery["current"]))
    for lag in range(1, int(recovery["lagCount"]) + 1):
        recovery_names.extend(f"lag{lag}.{name}" for name in cast(list[str], recovery["lag"]))
    for window in cast(list[int], recovery["rollingWindows"]):
        for signal in cast(list[str], recovery["rollingSignals"]):
            recovery_names.extend(
                f"rolling{window}.{signal}.{statistic}"
                for statistic in cast(list[str], recovery["rollingStatistics"])
            )
    return sleep_names, recovery_names


def swift_array(values: list[str] | list[int] | list[float]) -> str:
    rendered = [json.dumps(value) for value in values]
    return "[" + ", ".join(rendered) + "]"


def generate_swift(manifest: dict[str, Any], sleep: list[str], recovery: list[str]) -> str:
    sleep_manifest = cast(dict[str, Any], manifest["sleep"])
    recovery_manifest = cast(dict[str, Any], manifest["recovery"])
    recovery_index = {name: index for index, name in enumerate(recovery)}

    def component_indices(signal: str) -> list[int]:
        return [
            index
            for index, name in enumerate(recovery)
            if name == f"current.{signal}"
            or (name.startswith("lag") and name.endswith(f".{signal}"))
            or (name.startswith("rolling") and f".{signal}." in name)
        ]

    sleep_component = list(range(len(sleep))) + component_indices("sleepScore")
    baseline_window = int(recovery_manifest["baselineWindow"])
    return f"""// Generated by Tools/generate_model_features.py. Do not edit.
import Foundation

enum GeneratedModelFeatures {{
    enum Sleep {{
        static let version = {json.dumps(str(sleep_manifest["version"]))}
        static let names = {swift_array(sleep)}
        static let featureCount = names.count
        static let durationIndex = {sleep.index("current.durationMinutes")}
        static let efficiencyIndex = {sleep.index("current.efficiencyPercentage")}
        static let lag1DurationIndex = {sleep.index("lag1.durationMinutes")}
        static let lag1EfficiencyIndex = {sleep.index("lag1.efficiencyPercentage")}
        static let agreementWeights = {swift_array(cast(list[float], sleep_manifest["agreementWeights"]))}
    }}

    enum Recovery {{
        static let version = {json.dumps(str(recovery_manifest["version"]))}
        static let names = {swift_array(recovery)}
        static let featureCount = names.count
        static let currentHRVIndex = {recovery_index["current.hrv"]}
        static let currentRHRIndex = {recovery_index["current.rhr"]}
        static let currentStepsIndex = {recovery_index["current.steps"]}
        static let currentSleepScoreIndex = {recovery_index["current.sleepScore"]}
        static let lag1HRVIndex = {recovery_index["lag1.hrv"]}
        static let lag1RHRIndex = {recovery_index["lag1.rhr"]}
        static let rolling7HRVMeanIndex = {recovery_index["rolling7.hrv.mean"]}
        static let hrvIndices = {swift_array(component_indices("hrv"))}
        static let rhrIndices = {swift_array(component_indices("rhr"))}
        static let stepsIndices = {swift_array(component_indices("steps"))}
        static let sleepIndices = {swift_array(sleep_component)}
        static let hrvBaselineIndex = {recovery_index[f"rolling{baseline_window}.hrv.mean"]}
        static let rhrBaselineIndex = {recovery_index[f"rolling{baseline_window}.rhr.mean"]}
        static let stepsBaselineIndex = {recovery_index[f"rolling{baseline_window}.steps.mean"]}
        static let sleepBaselineIndex = {recovery_index[f"rolling{baseline_window}.sleepScore.mean"]}
    }}
}}
"""


def generate_python(manifest: dict[str, Any], sleep: list[str], recovery: list[str]) -> str:
    sleep_manifest = cast(dict[str, Any], manifest["sleep"])
    recovery_manifest = cast(dict[str, Any], manifest["recovery"])
    return f"""# Generated by Tools/generate_model_features.py. Do not edit.
SLEEP_FEATURE_VERSION = {json.dumps(str(sleep_manifest["version"]))}
SLEEP_FEATURE_NAMES = {sleep!r}
SLEEP_FEATURE_COUNT = len(SLEEP_FEATURE_NAMES)
SLEEP_AGREEMENT_WEIGHTS = {tuple(cast(list[float], sleep_manifest["agreementWeights"]))!r}

RECOVERY_FEATURE_VERSION = {json.dumps(str(recovery_manifest["version"]))}
RECOVERY_FEATURE_NAMES = {recovery!r}
RECOVERY_FEATURE_COUNT = len(RECOVERY_FEATURE_NAMES)
RECOVERY_INDEX = {{name: index for index, name in enumerate(RECOVERY_FEATURE_NAMES)}}
"""


def generate_golden(sleep: list[str], recovery: list[str]) -> str:
    duration = 480.0
    efficiency = 95.0
    start_minute = 1410.0
    end_minute = 450.0
    sleep_input: dict[str, object] = {
        "dateKey": "2026-01-08",
        "durationMinutes": duration,
        "efficiencyPercentage": efficiency,
        "startMinute": start_minute,
        "endMinute": end_minute,
    }
    current_sleep: dict[str, float] = {
        "durationMinutes": duration,
        "efficiencyPercentage": efficiency,
        "startSin": math.sin(2 * math.pi * start_minute / 1440),
        "startCos": math.cos(2 * math.pi * start_minute / 1440),
        "endSin": math.sin(2 * math.pi * end_minute / 1440),
        "endCos": math.cos(2 * math.pi * end_minute / 1440),
    }

    def sleep_value(name: str) -> float:
        field = name.rsplit(".", maxsplit=1)[-1]
        if name.startswith("current."):
            return float(current_sleep[field])
        if name.startswith("lag"):
            if field in ("durationMinutes", "efficiencyPercentage"):
                return float(current_sleep[field])
            return 0.0
        if field == "durationMean4":
            return duration
        if field == "efficiencyMean4":
            return efficiency
        if "StandardDeviation" in field:
            return 0.0
        return 100.0

    sleep_expected = [sleep_value(name) for name in sleep]
    recovery_input: dict[str, object] = {
        **sleep_input,
        "hrv": 60.0,
        "rhr": 50.0,
        "steps": 8000.0,
        "sleepScore": 85.0,
    }
    current_recovery: dict[str, float] = {
        "hrv": 60.0,
        "rhr": 50.0,
        "steps": 8000.0,
        "sleepScore": 85.0,
    }

    def recovery_value(name: str) -> float:
        if name.startswith("sleep."):
            return sleep_expected[sleep.index(name.removeprefix("sleep."))]
        field = name.split(".")[1]
        if name.startswith("current."):
            return current_recovery[field]
        if name.startswith("lag"):
            return 0.0 if field == "dayGap" else current_recovery[field]
        statistic = name.rsplit(".", maxsplit=1)[-1]
        if statistic == "mean":
            return current_recovery[field]
        if statistic == "ratio":
            return 1.0
        return 0.0

    payload = {
        "schemaVersion": 1,
        "sleep": {
            "input": sleep_input,
            "featureNames": sleep,
            "features": sleep_expected,
        },
        "recovery": {
            "input": recovery_input,
            "featureNames": recovery,
            "features": [recovery_value(name) for name in recovery],
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def formatted(content: str, suffix: str, root: Path) -> str:
    if suffix == ".json":
        return content
    with tempfile.TemporaryDirectory(prefix="whoop-model-features.") as directory:
        candidate = Path(directory) / f"Generated{suffix}"
        candidate.write_text(content, encoding="utf-8")
        command = (
            [
                "xcrun",
                "swift-format",
                "format",
                "--configuration",
                str(root / ".swift-format"),
                "--in-place",
                str(candidate),
            ]
            if suffix == ".swift"
            else [
                "ruff",
                "format",
                "--config",
                str(root / "pyproject.toml"),
                str(candidate),
            ]
        )
        subprocess.run(command, check=True, capture_output=True, text=True)
        return candidate.read_text(encoding="utf-8")


def write_or_check(path: Path, content: str, check: bool, root: Path) -> None:
    content = formatted(content, path.suffix, root)
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"Generated model feature contract is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    manifest = load_manifest(root / "Tools/model_features.json")
    sleep, recovery = expanded_names(manifest)
    if len(sleep) != 50 or len(recovery) != 169:
        raise SystemExit(
            f"Unexpected generated feature counts: sleep={len(sleep)}, recovery={len(recovery)}"
        )
    write_or_check(
        root / "SleepApp/GeneratedModelFeatures.swift",
        generate_swift(manifest, sleep, recovery),
        args.check,
        root,
    )
    write_or_check(
        root / "Tools/generated_model_features.py",
        generate_python(manifest, sleep, recovery),
        args.check,
        root,
    )
    write_or_check(
        root / "SleepPrivateTests/Fixtures/model-feature-golden.json",
        generate_golden(sleep, recovery),
        args.check,
        root,
    )


if __name__ == "__main__":
    main()
